"""Generate agent_traces/INDEX.md from the development-agent traces actually present.

Why this exists
---------------
`AGENT_USE.md` is the coding-agent disclosure the challenge requires, and a disclosure that lists
files by hand can drift from the files in the repository. The rest of this project generates its
claims from artefacts (`tools/check_results.py`, `eval/report_components.py`), so the trace index is
generated the same way: it enumerates what is on disk, records size and a SHA-256 prefix, and refuses
to produce an index at all if the directory is empty. A judge running this command gets the same
table that is committed, or a loud failure.

It also greps every trace for common credential shapes and refuses to write the index if any hit,
because ground rule 08 keeps credentials out of the submission and "I checked by eye" is not a check.

Usage
-----
    python tools/collect_agent_traces.py            # print the index and the secret scan
    python tools/collect_agent_traces.py --write    # also write agent_traces/INDEX.md

Exit codes
----------
    0  traces present, no secret-shaped strings found
    1  no traces present, or a possible secret found (index not written)
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
TRACES = ROOT / "agent_traces"
SUFFIXES = {".md", ".jsonl", ".json", ".txt", ".log", ".html"}

# Deliberately crude and noisy: a false positive costs 10 seconds, a miss costs the integrity check.
SECRET_PATTERNS = [
    ("OpenAI-style key", re.compile(r"\bsk-[A-Za-z0-9_\-]{20,}")),
    ("Anthropic-style key", re.compile(r"\bsk-ant-[A-Za-z0-9_\-]{20,}")),
    ("GitHub token", re.compile(r"\bgh[pousr]_[A-Za-z0-9]{20,}")),
    ("AWS access key id", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("bearer header", re.compile(r"(?i)authorization\s*:\s*bearer\s+\S{12,}")),
    ("assigned secret", re.compile(r"(?i)\b(api[_-]?key|secret|password|passwd|token)\s*[=:]\s*"
                                   r"['\"][^'\"\s]{12,}['\"]")),
    ("postgres URI with password", re.compile(r"postgres(?:ql)?://[^\s:@/]+:[^\s@/]{3,}@")),
]


def sha256_prefix(path: pathlib.Path, length: int = 12) -> str:
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    return digest[:length]


def human_size(n: int) -> str:
    if n < 1024:
        return f"{n} B"
    if n < 1024 * 1024:
        return f"{n / 1024:.0f} KB"
    return f"{n / (1024 * 1024):.1f} MB"


def find_traces() -> list[pathlib.Path]:
    if not TRACES.is_dir():
        return []
    return sorted(
        p for p in TRACES.rglob("*")
        if p.is_file() and p.suffix.lower() in SUFFIXES and p.name != "INDEX.md"
    )


def scan_secrets(paths: list[pathlib.Path]) -> list[tuple[pathlib.Path, int, str]]:
    hits: list[tuple[pathlib.Path, int, str]] = []
    for path in paths:
        try:
            text = path.read_text(errors="replace")
        except OSError:
            continue
        for lineno, line in enumerate(text.splitlines(), start=1):
            for label, pattern in SECRET_PATTERNS:
                if pattern.search(line):
                    hits.append((path, lineno, label))
    return hits


def render(paths: list[pathlib.Path]) -> str:
    total = sum(p.stat().st_size for p in paths)
    plural = "s" if len(paths) != 1 else ""
    lines = [
        "# Development-agent trace index\n",
        f"Generated by `tools/collect_agent_traces.py` on "
        f"{dt.datetime.now(dt.timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}. "
        "Do not edit by hand; re-run the command.\n",
        f"{len(paths)} trace file{plural}, {human_size(total)} total. These are the sessions with the "
        "coding agent that *built* Migration Sentinel. The runtime traces of the five agents that "
        "*run inside* it are separate and live in `trajectories/` and "
        "`docs/AGENT_TRAJECTORIES.md`.\n",
        "| file | size | sha256 (first 12) |",
        "|---|---|---|",
    ]
    for path in paths:
        rel = path.relative_to(ROOT).as_posix()
        lines.append(f"| [`{rel}`]({path.relative_to(TRACES).as_posix()}) | "
                     f"{human_size(path.stat().st_size)} | `{sha256_prefix(path)}` |")
    lines += [
        "",
        "Secret scan: `tools/collect_agent_traces.py` greps every file above for key, token and "
        "connection-string shapes and refuses to write this index on a hit. It passed for this "
        "index. See `AGENT_USE.md` for what these sessions cover and, more importantly, what they "
        "do not.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the development-agent trace index.")
    parser.add_argument("--write", action="store_true", help="write agent_traces/INDEX.md")
    args = parser.parse_args(argv)

    paths = find_traces()
    if not paths:
        print(f"No trace files found under {TRACES.relative_to(ROOT)}/.", file=sys.stderr)
        print("Export your coding-agent sessions into that directory "
              f"({', '.join(sorted(SUFFIXES))}) and re-run. Refusing to write an empty index: an "
              "index that lists nothing reads as a disclosure when it is an absence.", file=sys.stderr)
        return 1

    hits = scan_secrets(paths)
    if hits:
        print("Possible secrets found. INDEX.md not written. Redact these first:", file=sys.stderr)
        for path, lineno, label in hits[:40]:
            print(f"  {path.relative_to(ROOT).as_posix()}:{lineno}  {label}", file=sys.stderr)
        return 1

    text = render(paths)
    print(text)
    print(f"secret scan: {len(paths)} files, 0 hits across {len(SECRET_PATTERNS)} patterns")
    if args.write:
        out = TRACES / "INDEX.md"
        out.write_text(text)
        print(f"wrote {out.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
